### ISSUE TITLE
Is it possible to swap two values at known indices?

### ISSUE THREAD

**Issue by PartyWumpus** [HarrisonMc555/array2d#18]
If I was using a vec of vecs, this would be reasonably easy:

if they're in the same inner vec then just
```rust
arr.swap(index1, index2)
```

and if they're in different vecs then i can get a mutable reference to each and just
```rust
std::mem::swap(&mut value1, &mut value2)
```

I can't figure out a way to do this with the API you make available, even with `std::ptr::swap`

**Comment by HarrisonMc555** [comment]
This is a good idea! I tried to go through the methods on slices and `Vec` and have an equivalent method for all the ones that made sense, but I missed this one. I just merged a pull request and I plan on making a release soon.
