### ISSUE TITLE
Iterator over every element with current position

### ISSUE THREAD

**Issue by amarao** [HarrisonMc555/array2d#5]
I start to use Array2D, and it looks nice, but I found it misses a special case.

I need to iterate over every element of the array, but I need to know the position (x, y) for element I work with. I can (and I will) do it with enumeration, but some 'ready-made' method would be nice.

I think it may be something like `iter_elements_enumerated()`, yielding `(x,y, element)` tuple.

**Comment by HarrisonMc555** [comment]
Thanks for your input! This is quite timely because I actually just encountered a need for this myself! I will be pushing my first pass at an implementation for this to a branch in the next day or so. Feel free to take a look and see if it would be sufficient for your use case!

**Comment by plaptov** [comment]
Any plans for merge? It would be useful.

**Comment by HarrisonMc555** [comment]
Sorry for the (2 year!) delay. Oops. Merged now :)
