### ISSUE TITLE
Mutable iterators

### ISSUE THREAD

**Issue by amarao** [HarrisonMc555/array2d#6]
I continue to use array2d, and now I found it lacks mutable iterators. There is a `get_mut` function, but there are no iterators whose yield mutable references to each element.

I think something like `elements_column_major_iter_mut()` may be good.

**Comment by HarrisonMc555** [comment]
That's a great idea! Not sure how that hadn't occurred to me yet. I'll put it on the list of things to work on :smiley:

**Comment by krojew** [comment]
Just stumbled upon this too. Would be great to have mutable iterators.

**Comment by HarrisonMc555** [comment]
I've decided against adding mutable iterators for the time being. Please see the discussion in #13 for my reasoning. I'm willing to open another discussion in the future, but it would need to address the issues I raised there.

Thank you for your interest!
